# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.7

env:
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=py37
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=pypy

install: pip install tox-travis
script: tox